application: irandomlywrotethisforyou2
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /stylesheets
  static_dir: stylesheets

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest