runtime: go
api_version: go1

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: always

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always

- url: /css
  static_dir: static/css
  secure: always

- url: /js
  static_dir: static/js
  secure: always

- url: /.*
  script: _go_app
  secure: always

env_variables:
  API_KEY: ""
