runtime: go
api_version: go1

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /.*
  script: _go_app
