runtime: go112

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: always

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always

- url: /stay
  static_files: static/stay.html
  upload: static/stay.html
  secure: always

- url: /bri
  static_files: static/bri.html
  upload: static/bri.html
  secure: always

- url: /css
  static_dir: static/css
  secure: always

- url: /js
  static_dir: static/js
  secure: always

- url: /.*
  script: auto
  secure: always
